<?php

/**
 * @file
 * Contains mailhogger.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailhogger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailhogger module.
    case 'help.page.mailhogger':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('View MailHog messages') . '</p>';
      return $output;

    default:
  }
}
